### ISSUE TITLE
mac端在选择proversion文件后， bundleid默认用的proversion中的id，并且不能再修改，这个可以修改成可修改么

### ISSUE THREAD

**Issue by afsfge** [even-cheng/ECSigner#10]
RT.

**Comment by even-cheng** [comment]
您可以下载源码修改




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "even-cheng/ECSigner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月15日(星期二) 中午11:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[even-cheng/ECSigner] mac端在选择proversion文件后， bundleid默认用的proversion中的id，并且不能再修改，这个可以修改成可修改么 (Issue #10)





 
RT.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afsfge** [comment]
不会这块的开发。。。 没事，我用的也不多， 谢啦哈

**Comment by even-cheng** [comment]
已修改
