### ISSUE TITLE
支持一键替换原包icon。 试了几个项目都是失败。

### ISSUE THREAD

**Issue by LiuSky** [even-cheng/ECSigner#14]
支持一键替换原包icon。 试了几个项目都是失败。。作者能否给个详细的教程

**Comment by even-cheng** [comment]
用release里面的mac高级版试试发自我的 iPhone在 2023年9月4日，23:51，阿嘴 ***@***.***> 写道：﻿
支持一键替换原包icon。 试了几个项目都是失败。。作者能否给个详细的教程

**Comment by LiuSky** [comment]
我就是用Mac release的版本。

**Comment by even-cheng** [comment]
选择安装包， 选择重签名证书，选择新的图标，开始签名，签完的包应该就可以的。发自我的 iPhone在 2023年9月4日，23:51，阿嘴 ***@***.***> 写道：﻿
支持一键替换原包icon。 试了几个项目都是失败。。作者能否给个详细的教程

**Comment by LiuSky** [comment]
<img width="185" alt="截屏2023-09-06 20 38 52" src="https://github.com/even-cheng/ECSigner/assets/3087745/5e598d35-ec8d-4c8b-a476-8048a2e0e414">
替换一直出现这个。任何项目

**Comment by even-cheng** [comment]
试试ios版发自我的 iPhone在 2024年7月31日，07:43，阿嘴 ***@***.***> 写道：﻿
Closed #14 as not planned.
