### ISSUE TITLE
可以改成iOS版吗

### ISSUE THREAD

**Issue by xljhd** [even-cheng/ECSigner#6]
大佬你好，这个可以在手机上直接签名吗（能不能改成iOS版本），还是说一定要Mac的支持？

**Comment by even-cheng** [comment]
只支持mac，由于手机的沙盒限制只有越狱之后才可能在手机端进行签名

发自我的iPhone

**Comment by xljhd** [comment]
大佬，你的意思如果手机越狱了就可以实现？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Even_cheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上9:20
收件人:&nbsp;"even-cheng/ECSigner"<ECSigner@noreply.github.com&gt;;
抄送:&nbsp;"夏"<728599123@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [even-cheng/ECSigner] 可以改成iOS版吗 (#6)





 只支持mac，由于手机的沙盒限制只有越狱之后才可能在手机端进行签名 
 
 发自我的iPhone 
 
 &gt; 在 2020年5月19日，17:50，嘎嘎嘎 <notifications@github.com&gt; 写道： 
 &gt;  
 &gt; ﻿ 
 &gt; 大佬你好，这个可以在手机上直接签名吗（能不能改成iOS版本），还是说一定要Mac的支持？ 
 &gt;  
 &gt; — 
 &gt; You are receiving this because you are subscribed to this thread. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by even-cheng** [comment]
越狱环境下安装第三方资源可以实现，可以具体了解一下re签名安装

发自我的iPhone

**Comment by even-cheng** [comment]
> 大佬你好，这个可以在手机上直接签名吗（能不能改成iOS版本），还是说一定要Mac的支持？

iOS版下载地址：[release](https://github.com/even-cheng/ECSigner/releases/tag/5.0)
